export enum FilterMatchModeEnum {
  STARTS_WITH = 'startsWith',
  CONTAINS = 'contains',
  NOT_CONTAINS = 'notContains',
  ENDS_WITH = 'endsWith',
  EQUALS = 'equals',
  NOT_EQUALS = 'notEquals',
  IN = 'in',
  LESS_THAN = 'lt',
  LESS_THAN_OR_EQUAL_TO = 'lte',
  GREATER_THAN = 'gt',
  GREATER_THAN_OR_EQUAL_TO = 'gte',
  BETWEEN = 'between',
  IS = 'is',
  IS_NOT = 'isNot',
  BEFORE = 'before',
  AFTER = 'after',
  DATE_IS = 'dateIs',
  DATE_IS_NOT = 'dateIsNot',
  DATE_BEFORE = 'dateBefore',
  DATE_AFTER = 'dateAfter',
}

export const filterMatchModeLabels: Record<FilterMatchModeEnum, string> = {
  after: 'After',
  before: 'Before',
  between: 'Between',
  contains: 'Contains',
  dateAfter: 'Date After',
  dateBefore: 'Date Before',
  dateIs: 'Date Is',
  dateIsNot: 'Date Is Not',
  endsWith: 'Ends With',
  equals: 'Equals',
  gt: 'Greater Than',
  gte: 'Greater Than Or Equal To',
  in: 'In',
  is: 'Is',
  isNot: 'Is Not',
  lt: 'Less Than',
  lte: 'Less Than Or Equal To',
  notContains: 'Not Contains',
  notEquals: 'Not Equals',
  startsWith: 'Starts With',
} as const;

export const filterMatchModeOptions = {
  text: [
    FilterMatchModeEnum.STARTS_WITH,
    FilterMatchModeEnum.CONTAINS,
    FilterMatchModeEnum.NOT_CONTAINS,
    FilterMatchModeEnum.ENDS_WITH,
    FilterMatchModeEnum.EQUALS,
    FilterMatchModeEnum.NOT_EQUALS,
  ],
  numeric: [
    FilterMatchModeEnum.EQUALS,
    FilterMatchModeEnum.NOT_EQUALS,
    FilterMatchModeEnum.LESS_THAN,
    FilterMatchModeEnum.LESS_THAN_OR_EQUAL_TO,
    FilterMatchModeEnum.GREATER_THAN,
    FilterMatchModeEnum.GREATER_THAN_OR_EQUAL_TO,
    FilterMatchModeEnum.BETWEEN,
  ],
  date: [FilterMatchModeEnum.DATE_IS, FilterMatchModeEnum.DATE_IS_NOT, FilterMatchModeEnum.DATE_BEFORE, FilterMatchModeEnum.DATE_AFTER],
} as const;
